export type SupportedBreed = { id: string; name: string };

export const SUPPORTED_BREEDS: SupportedBreed[] = [
  { id: "affenpinscher", name: "Affenpinscher" },
  { id: "afghan-hound", name: "Afghan Hound" },
  { id: "african-hunting-dog", name: "African Hunting Dog" },
  { id: "airedale", name: "Airedale" },
  { id: "american-staffordshire-terrier", name: "American Staffordshire Terrier" },
  { id: "appenzeller", name: "Appenzeller" },
  { id: "australian-terrier", name: "Australian Terrier" },
  { id: "basenji", name: "Basenji" },
  { id: "basset", name: "Basset" },
  { id: "beagle", name: "Beagle" },
  { id: "bedlington-terrier", name: "Bedlington Terrier" },
  { id: "bernese-mountain-dog", name: "Bernese Mountain Dog" },
  { id: "black-and-tan-coonhound", name: "Black-And-Tan Coonhound" },
  { id: "blenheim-spaniel", name: "Blenheim Spaniel" },
  { id: "bloodhound", name: "Bloodhound" },
  { id: "bluetick", name: "Bluetick" },
  { id: "border-collie", name: "Border Collie" },
  { id: "border-terrier", name: "Border Terrier" },
  { id: "borzoi", name: "Borzoi" },
  { id: "boston-bull", name: "Boston Bull" },
  { id: "bouvier-des-flandres", name: "Bouvier Des Flandres" },
  { id: "boxer", name: "Boxer" },
  { id: "brabancon-griffon", name: "Brabancon Griffon" },
  { id: "briard", name: "Briard" },
  { id: "brittany-spaniel", name: "Brittany Spaniel" },
  { id: "bull-mastiff", name: "Bull Mastiff" },
  { id: "cairn", name: "Cairn" },
  { id: "cardigan", name: "Cardigan" },
  { id: "chesapeake-bay-retriever", name: "Chesapeake Bay Retriever" },
  { id: "chihuahua", name: "Chihuahua" },
  { id: "chow", name: "Chow" },
  { id: "clumber", name: "Clumber" },
  { id: "cocker-spaniel", name: "Cocker Spaniel" },
  { id: "collie", name: "Collie" },
  { id: "curly-coated-retriever", name: "Curly-Coated Retriever" },
  { id: "dandie-dinmont", name: "Dandie Dinmont" },
  { id: "dhole", name: "Dhole" },
  { id: "dingo", name: "Dingo" },
  { id: "doberman", name: "Doberman" },
  { id: "english-foxhound", name: "English Foxhound" },
  { id: "english-setter", name: "English Setter" },
  { id: "english-springer", name: "English Springer" },
  { id: "entlebucher", name: "EntleBucher" },
  { id: "eskimo-dog", name: "Eskimo Dog" },
  { id: "flat-coated-retriever", name: "Flat-Coated Retriever" },
  { id: "french-bulldog", name: "French Bulldog" },
  { id: "german-shepherd", name: "German Shepherd" },
  { id: "german-short-haired-pointer", name: "German Short-Haired Pointer" },
  { id: "giant-schnauzer", name: "Giant Schnauzer" },
  { id: "golden-retriever", name: "Golden Retriever" },
  { id: "gordon-setter", name: "Gordon Setter" },
  { id: "great-dane", name: "Great Dane" },
  { id: "great-pyrenees", name: "Great Pyrenees" },
  { id: "greater-swiss-mountain-dog", name: "Greater Swiss Mountain Dog" },
  { id: "groenendael", name: "Groenendael" },
  { id: "ibizan-hound", name: "Ibizan Hound" },
  { id: "irish-setter", name: "Irish Setter" },
  { id: "irish-terrier", name: "Irish Terrier" },
  { id: "irish-water-spaniel", name: "Irish Water Spaniel" },
  { id: "irish-wolfhound", name: "Irish Wolfhound" },
  { id: "italian-greyhound", name: "Italian Greyhound" },
  { id: "japanese-spaniel", name: "Japanese Spaniel" },
  { id: "keeshond", name: "Keeshond" },
  { id: "kelpie", name: "Kelpie" },
  { id: "kerry-blue-terrier", name: "Kerry Blue Terrier" },
  { id: "komondor", name: "Komondor" },
  { id: "kuvasz", name: "Kuvasz" },
  { id: "labrador-retriever", name: "Labrador Retriever" },
  { id: "lakeland-terrier", name: "Lakeland Terrier" },
  { id: "leonberg", name: "Leonberg" },
  { id: "lhasa", name: "Lhasa" },
  { id: "malamute", name: "Malamute" },
  { id: "malinois", name: "Malinois" },
  { id: "maltese-dog", name: "Maltese Dog" },
  { id: "mexican-hairless", name: "Mexican Hairless" },
  { id: "miniature-pinscher", name: "Miniature Pinscher" },
  { id: "miniature-poodle", name: "Miniature Poodle" },
  { id: "miniature-schnauzer", name: "Miniature Schnauzer" },
  { id: "newfoundland", name: "Newfoundland" },
  { id: "norfolk-terrier", name: "Norfolk Terrier" },
  { id: "norwegian-elkhound", name: "Norwegian Elkhound" },
  { id: "norwich-terrier", name: "Norwich Terrier" },
  { id: "old-english-sheepdog", name: "Old English Sheepdog" },
  { id: "otterhound", name: "Otterhound" },
  { id: "papillon", name: "Papillon" },
  { id: "pekinese", name: "Pekinese" },
  { id: "pembroke", name: "Pembroke" },
  { id: "pomeranian", name: "Pomeranian" },
  { id: "pug", name: "Pug" },
  { id: "redbone", name: "Redbone" },
  { id: "rhodesian-ridgeback", name: "Rhodesian Ridgeback" },
  { id: "rottweiler", name: "Rottweiler" },
  { id: "saint-bernard", name: "Saint Bernard" },
  { id: "saluki", name: "Saluki" },
  { id: "samoyed", name: "Samoyed" },
  { id: "schipperke", name: "Schipperke" },
  { id: "scotch-terrier", name: "Scotch Terrier" },
  { id: "scottish-deerhound", name: "Scottish Deerhound" },
  { id: "sealyham-terrier", name: "Sealyham Terrier" },
  { id: "shetland-sheepdog", name: "Shetland Sheepdog" },
  { id: "shih-tzu", name: "Shih-Tzu" },
  { id: "siberian-husky", name: "Siberian Husky" },
  { id: "silky-terrier", name: "Silky Terrier" },
  { id: "soft-coated-wheaten-terrier", name: "Soft-Coated Wheaten Terrier" },
  { id: "staffordshire-bullterrier", name: "Staffordshire Bullterrier" },
  { id: "standard-poodle", name: "Standard Poodle" },
  { id: "standard-schnauzer", name: "Standard Schnauzer" },
  { id: "sussex-spaniel", name: "Sussex Spaniel" },
  { id: "tibetan-mastiff", name: "Tibetan Mastiff" },
  { id: "tibetan-terrier", name: "Tibetan Terrier" },
  { id: "toy-poodle", name: "Toy Poodle" },
  { id: "toy-terrier", name: "Toy Terrier" },
  { id: "vizsla", name: "Vizsla" },
  { id: "walker-hound", name: "Walker Hound" },
  { id: "weimaraner", name: "Weimaraner" },
  { id: "welsh-springer-spaniel", name: "Welsh Springer Spaniel" },
  { id: "west-highland-white-terrier", name: "West Highland White Terrier" },
  { id: "whippet", name: "Whippet" },
  { id: "wire-haired-fox-terrier", name: "Wire-Haired Fox Terrier" },
  { id: "yorkshire-terrier", name: "Yorkshire Terrier" },
];
